<?php

return [
    'MAIL_ADD' => ':USER:MAIL_ADD',

    'SECKILL_ACTIVITY_GOODS_STOCK_QUEUE'  => ':ACTIVITY:SECKILL:GOODS_STOCK_QUEUE',
    'SECKILL_ACTIVITY_USER_WAIT_QUEUE'    => ':ACTIVITY:SECKILL:USER_WAIT_QUEUE',
    'SECKILL_ACTIVITY_USER_SUCCESS_QUEUE' => ':ACTIVITY:SECKILL:USER_SUCCESS_QUEUE',

    'REDIS_USER_HYPER_LOG_LOG_1' => ':REDIS:HYPER_LOG_LOG_1',
    'REDIS_USER_HYPER_LOG_LOG_2' => ':REDIS:HYPER_LOG_LOG_2',
    'REDIS_USER_HYPER_LOG_LOG_3' => ':REDIS:HYPER_LOG_LOG_3',
];
